sudo: required
language: java
services:
    - docker
    - maven

before_install:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - docker build -t screenpost-api -f Dockerfile .