package com.screenpost.api.pojo;
// Generated 1 Jul, 2020 2:00:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContainerContent generated by hbm2java
 */
@Entity
@Table(name = "container_content")
public class ContainerContent implements java.io.Serializable {

	private ContainerContentId id;
	private Content contentByContainerId;
	private Content contentByContentId;
	private int sno;

	public ContainerContent() {
	}

	public ContainerContent(ContainerContentId id, Content contentByContainerId, Content contentByContentId,
			int sno) {
		this.id = id;
		this.contentByContainerId = contentByContainerId;
		this.contentByContentId = contentByContentId;
		this.sno = sno;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "contentId", column = @Column(name = "content_id", nullable = false)),
			@AttributeOverride(name = "containerId", column = @Column(name = "container_id", nullable = false)) })
	public ContainerContentId getId() {
		return this.id;
	}

	public void setId(ContainerContentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "container_id", nullable = false, insertable = false, updatable = false)
	public Content getContentByContainerId() {
		return this.contentByContainerId;
	}

	public void setContentByContainerId(Content contentByContainerId) {
		this.contentByContainerId = contentByContainerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_id", nullable = false, insertable = false, updatable = false)
	public Content getContentByContentId() {
		return this.contentByContentId;
	}

	public void setContentByContentId(Content contentByContentId) {
		this.contentByContentId = contentByContentId;
	}

	@Column(name = "sno", nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

}
