package com.screenpost.api.pojo;
// Generated 1 Jul, 2020 2:00:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContainerContentId generated by hbm2java
 */
@Embeddable
public class ContainerContentId implements java.io.Serializable {

	private int contentId;
	private int containerId;

	public ContainerContentId() {
	}

	public ContainerContentId(int contentId, int containerId) {
		this.contentId = contentId;
		this.containerId = containerId;
	}

	@Column(name = "content_id", nullable = false)
	public int getContentId() {
		return this.contentId;
	}

	public void setContentId(int contentId) {
		this.contentId = contentId;
	}

	@Column(name = "container_id", nullable = false)
	public int getContainerId() {
		return this.containerId;
	}

	public void setContainerId(int containerId) {
		this.containerId = containerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContainerContentId))
			return false;
		ContainerContentId castOther = (ContainerContentId) other;

		return (this.getContentId() == castOther.getContentId())
				&& (this.getContainerId() == castOther.getContainerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContentId();
		result = 37 * result + this.getContainerId();
		return result;
	}

}
