package com.screenpost.api.pojo;
// Generated 1 Jul, 2020 2:00:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContainerContentId generated by hbm2java
 */
@Embeddable
public class ScreenContentId implements java.io.Serializable {

	private int contentId;
	private int screenId;

	public ScreenContentId() {
	}

	public ScreenContentId(int contentId, int screenId) {
		this.contentId = contentId;
		this.screenId = screenId;
	}

	@Column(name = "content_id", nullable = false)
	public int getContentId() {
		return this.contentId;
	}

	public void setContentId(int contentId) {
		this.contentId = contentId;
	}

	@Column(name = "screen_id", nullable = false)
	public int getScreenId() {
		return this.screenId;
	}

	public void setScreenId(int screenId) {
		this.screenId = screenId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScreenContentId))
			return false;
		ScreenContentId castOther = (ScreenContentId) other;

		return (this.getContentId() == castOther.getContentId())
				&& (this.getScreenId() == castOther.getScreenId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContentId();
		result = 37 * result + this.getScreenId();
		return result;
	}

}
