package com.screenpost.api.pojo;
// Generated 1 Jul, 2020 2:00:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContainerContent generated by hbm2java
 */
@Entity
@Table(name = "screen_content")
public class ScreenContent implements java.io.Serializable {

	private ScreenContentId id;
	private int sno;
	private Screen screenByScreenId;
	private Content contentByContentId;

	public ScreenContent() {
	}

	public ScreenContent(ScreenContentId id, Screen screenByScreenId, Content contentByContentId) {
		this.id = id;
		this.screenByScreenId = screenByScreenId;
		this.contentByContentId = contentByContentId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "contentId", column = @Column(name = "content_id", nullable = false)),
			@AttributeOverride(name = "screenId", column = @Column(name = "screen_id", nullable = false)) })
	public ScreenContentId getId() {
		return this.id;
	}

	public void setId(ScreenContentId id) {
		this.id = id;
	}

	@Column(name = "sno")
	public int getSno() {
		return sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screen_id", nullable = false, insertable = false, updatable = false)
	public Screen getScreenByScreenId() {
		return this.screenByScreenId;
	}

	public void setScreenByScreenId(Screen screenByScreenId) {
		this.screenByScreenId = screenByScreenId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_id", nullable = false, insertable = false, updatable = false)
	public Content getContentByContentId() {
		return this.contentByContentId;
	}

	public void setContentByContentId(Content contentByContentId) {
		this.contentByContentId = contentByContentId;
	}

}
