package com.screenpost.api.pojo;
// Generated 1 Jul, 2020 2:00:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile")
public class UserProfile implements java.io.Serializable {

	private int userId;
	private OauthUserDet oauthUserDet;
	private String firstName;
	private String lastName;
	private String companyName;

	public UserProfile() {
	}

	public UserProfile(OauthUserDet oauthUserDet) {
		this.oauthUserDet = oauthUserDet;
	}

	public UserProfile(OauthUserDet oauthUserDet, String firstName, String lastName, String companyName) {
		this.oauthUserDet = oauthUserDet;
		this.firstName = firstName;
		this.lastName = lastName;
		this.companyName = companyName;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "oauthUserDet"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public OauthUserDet getOauthUserDet() {
		return this.oauthUserDet;
	}

	public void setOauthUserDet(OauthUserDet oauthUserDet) {
		this.oauthUserDet = oauthUserDet;
	}

	@Column(name = "first_name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "company_name")
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

}
